Cloud hosted adjustments
OpenLiberty/guide-rest-client-angularjs pull request #98
Opened 2021-09-30 15:01 UTC by davidwyao

2021-10-25 16:07 UTC, gkwan-ibm reviewed
@davidwyao 
- at line 84, and 198 " to specify the location of **artists.json** on the cloud:" is not clear enough
- at line 151, `cd /home/projects/...` -> `cd /home/project/...`
- at line 165-168, suggest to use curl command
- at line 200, use full path of consume-rest.js instead starting from the src directory
- at line 301, try add a backtick at "**`http"
  - and "ai`**", so the no direct link is shown on the lab

2021-10-26 16:39 UTC, dmuelle requested changes
Looks good- just a few comments on formatting syntax

2021-10-26 16:39 UTC, dmuelle commented on README.adoc
> +In this IBM cloud environment, you need to update the URL to access the **artists.json** in the **consume-rest.js** file.
generally, we use `monospace` for file names and **bold** for UI elements:

you need to update the URL to access the `artists.json` in the `consume-rest.js` file.

....go to the `finish` directory and update the `consume-rest.js` file:

2021-10-26 16:39 UTC, dmuelle commented on README.adoc
> +Run the following command to update the URL to access the **artists.json** in the **consume-rest.js** file:
see previous comment re monospace for file names

2021-10-26 16:39 UTC, dmuelle commented on README.adoc
> +Whenever you change your AngularJS implementation, the application root at **`http://accountname-9080.theiadocker-4.proxy.cognitiveclass.ai`** will
don't need bold for the URL

2021-10-26 16:53 UTC, gkwan-ibm commented on README.adoc
> +In this IBM cloud environment, you need to update the URL to access the **artists.json** in the **consume-rest.js** file.
unfortunately, SN(cloud-hosted) cannot show monospace nicely, so we use bold

2021-10-26 17:04 UTC, dmuelle commented on README.adoc
> +In this IBM cloud environment, you need to update the URL to access the **artists.json** in the **consume-rest.js** file.
ok- then disregard comments to that effect

2021-10-26 17:04 UTC, gkwan-ibm commented on README.adoc
> +Whenever you change your AngularJS implementation, the application root at **`http://accountname-9080.theiadocker-4.proxy.cognitiveclass.ai`** will
addressed

2021-10-26 17:06 UTC, dmuelle approved these changes
LGTM

2021-10-26 17:09 UTC, gkwan-ibm approved these changes

2021-11-30 20:16 UTC, merged